filter:
  excluded_paths:
    - 'test/*'

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    properties_in_camelcaps: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: false
      verify_parent_constraints: true
    simplify_boolean_return: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      within:
        brackets: true
      other:
        after_type_cast: false

tools:
  external_code_coverage: true